name: i-zxl
description: Blogging about zxl
meta_description: "Blogging about zxl"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://i-zxl.github.io/'
#google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://i-zxl.github.io'
author:         'zxl'
