name: Xinglai Zhao
description: Blogging about stuffs
meta_description: "Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
icon: "/assets/images/icon.png"
baseurl: /
domain_name: 'http://i-zxl.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
# Details for the RSS feed generator
url:            'http://i-zxl.github.io'
author:         'Xinglai Zhao'
