name: jacob
description: 赵兴来的博客
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
icon: "/assets/images/icon.png"
baseurl: /
domain_name: 'http://i-zxl.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
# Details for the RSS feed generator
url:            'http://i-zxl.github.io'
author:         'Xinglai Zhao'
